package com.redsun.platf.entity.sys;
// default package
// Generated 2010/8/17 下午 02:40:25 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * Sys120mId generated by hbm2java
 */
public class Sys120mId implements java.io.Serializable {


	private Date transStart;
	private String fileName;

	public Sys120mId() {
	}

	public Sys120mId(Date transStart, String fileName) {
		this.transStart = transStart;
		this.fileName = fileName;
	}

	public Date getTransStart() {
		return this.transStart;
	}

	public void setTransStart(Date transStart) {
		this.transStart = transStart;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Sys120mId))
			return false;
		Sys120mId castOther = (Sys120mId) other;

		return ((this.getTransStart() == castOther.getTransStart()) || (this
				.getTransStart() != null
				&& castOther.getTransStart() != null && this.getTransStart()
				.equals(castOther.getTransStart())))
				&& ((this.getFileName() == castOther.getFileName()) || (this
						.getFileName() != null
						&& castOther.getFileName() != null && this
						.getFileName().equals(castOther.getFileName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getTransStart() == null ? 0 : this.getTransStart()
						.hashCode());
		result = 37 * result
				+ (getFileName() == null ? 0 : this.getFileName().hashCode());
		return result;
	}
	
}
