package com.redsun.platf.entity.sys;

import java.util.Date;

import com.redsun.platf.entity.BaseEntity;

/**
 * OS-HOST與SID與對照表
 * Sys109m generated by hbm2java
 */
public class Sys109m extends BaseEntity implements java.io.Serializable {

	private Sys109mId sys109mId;
	private String sidDes;
	private String creUser;
	private Date creDate;
	private String maiUser;
	private Date maiDate;

	public Sys109m() {
	}

	public Sys109m(Sys109mId sys109mId) {
		this.sys109mId = sys109mId;
	}

	public Sys109m(Sys109mId id, String sidDes, String creUser, Date creDate,
			String maiUser, Date maiDate) {
		this.sys109mId = id;
		this.sidDes = sidDes;
		this.creUser = creUser;
		this.creDate = creDate;
		this.maiUser = maiUser;
		this.maiDate = maiDate;
	}

	public Sys109mId getSys109mId() {
		return this.sys109mId;
	}

	public void setId(Sys109mId id) {
		this.sys109mId = id;
	}

	public String getSidDes() {
		return this.sidDes;
	}

	public void setSidDes(String sidDes) {
		this.sidDes = sidDes;
	}

	public String getCreUser() {
		return this.creUser;
	}

	public void setCreUser(String creUser) {
		this.creUser = creUser;
	}

	public Date getCreDate() {
		return this.creDate;
	}

	public void setCreDate(Date creDate) {
		this.creDate = creDate;
	}

	public String getMaiUser() {
		return this.maiUser;
	}

	public void setMaiUser(String maiUser) {
		this.maiUser = maiUser;
	}

	public Date getMaiDate() {
		return this.maiDate;
	}

	public void setMaiDate(Date maiDate) {
		this.maiDate = maiDate;
	}

}
