package com.redsun.platf.entity.sys;


import java.io.Serializable;

import com.redsun.platf.entity.BaseEntity;

/**
 * 特殊程式維护表格 
 * Sys117m generated by hbm2java
 */
public class Sys117m extends BaseEntity implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String progid;
	private String progname;
	private String sysid;
	private String progState;


	public Sys117m() {
	}

	public Sys117m(String progid) {
		this.progid = progid;
	}

	public Sys117m(String progid, String progname, String sysid,
			String progState) {
		this.progid = progid;
		this.progname = progname;
		this.sysid = sysid;
		this.progState = progState;		
	}

	public String getProgid() {
		return this.progid;
	}

	public void setProgid(String progid) {
		this.progid = progid;
	}

	public String getProgname() {
		return this.progname;
	}

	public void setProgname(String progname) {
		this.progname = progname;
	}

	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	public String getProgState() {
		return this.progState;
	}

	public void setProgState(String progState) {
		this.progState = progState;
	}
	
}
