package com.redsun.platf.entity.sys;
// default package
// Generated 2010/8/17 下午 02:40:25 by Hibernate Tools 3.3.0.GA

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;

import org.hibernate.annotations.Type;

import com.redsun.platf.entity.BaseEntity;

/**
 * 轉檔記錄表格
 * Sys120m generated by hbm2java
 */


public class Sys120m extends BaseEntity implements Serializable {

	private Sys120mId sys120mId;
	private Long transRecs;
	private Long transFailRecs;
	private String transState;
	private String transDes;
	private String creUser;
	@Column(columnDefinition="timestamp")
	private Date creDat;
	private String maiUser;
	@Column(columnDefinition="timestamp")
	private Date maiDate;
	@Column(columnDefinition="timestamp")
	private Date transEnd;
	private String osHost;

	public Sys120m() {
	}

	public Sys120m(Sys120mId id) {
		this.sys120mId = id;
	}

	public Sys120m(Sys120mId id, Long transRecs, String transState,
			String transDes, String creUser, Date creDat, String maiUser,
			Date maiDate, Date transEnd, String osHost) {
		this.sys120mId = id;
		this.transRecs = transRecs;
		this.transState = transState;
		this.transDes = transDes;
		this.creUser = creUser;
		this.creDat = creDat;
		this.maiUser = maiUser;
		this.maiDate = maiDate;
		this.transEnd = transEnd;
		this.osHost = osHost;
	}

	

	public Long getTransRecs() {
		return this.transRecs;
	}

	public void setTransRecs(Long transRecs) {
		this.transRecs = transRecs;
	}

	public String getTransState() {
		return this.transState;
	}

	public void setTransState(String transState) {
		this.transState = transState;
	}

	public String getTransDes() {
		return this.transDes;
	}

	public void setTransDes(String transDes) {
		this.transDes = transDes;
	}

	public String getCreUser() {
		return this.creUser;
	}

	public void setCreUser(String creUser) {
		this.creUser = creUser;
	}

	public Date getCreDat() {
		return this.creDat;
	}

	public void setCreDat(Date creDat) {
		this.creDat = creDat;
	}

	public String getMaiUser() {
		return this.maiUser;
	}

	public void setMaiUser(String maiUser) {
		this.maiUser = maiUser;
	}

	public Date getMaiDate() {
		return this.maiDate;
	}

	public void setMaiDate(Date maiDate) {
		this.maiDate = maiDate;
	}

	public Date getTransEnd() {
		return this.transEnd;
	}

	public void setTransEnd(Date transEnd) {
		this.transEnd = transEnd;
	}

	public String getOsHost() {
		return this.osHost;
	}

	public void setOsHost(String osHost) {
		this.osHost = osHost;
	}
	
	public Sys120m getNewSys120m(Sys120m obj){
		Sys120m sys120m = new Sys120m(obj.getSys120mId());
		sys120m.setTransEnd(obj.getTransEnd());
		sys120m.setOsHost(obj.getOsHost());
		sys120m.setTransDes(obj.getTransDes());
		sys120m.setTransRecs(obj.getTransRecs());
		sys120m.setTransState(obj.getTransState());
		return sys120m;
	}

	public synchronized Long getTransFailRecs() {
		return transFailRecs;
	}

	public synchronized void setTransFailRecs(Long transFailRecs) {
		this.transFailRecs = transFailRecs;
	}

	public Sys120mId getSys120mId() {
	    return sys120mId;
	}

	public void setSys120mId(Sys120mId sys120mId) {
	    this.sys120mId = sys120mId;
	}
}
