package com.redsun.platf.entity.sys;
// default package
// Generated 2010/8/12 下午 05:52:38 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * Sys105mId generated by hbm2java
 */
public class Sys105mId implements java.io.Serializable {

	private String sid;
	private String dbUser;
	private Date executeTime;
	private String pid;

	public Sys105mId() {
	}

	public Sys105mId(String sid, String dbUser, Date executeTime, String pid) {
		this.sid = sid;
		this.dbUser = dbUser;
		this.executeTime = executeTime;
		this.pid = pid;
	}

	public String getSid() {
		return this.sid;
	}

	public void setSid(String sid) {
		this.sid = sid;
	}

	public String getDbUser() {
		return this.dbUser;
	}

	public void setDbUser(String dbUser) {
		this.dbUser = dbUser;
	}

	public Date getExecuteTime() {
		return this.executeTime;
	}

	public void setExecuteTime(Date executeTime) {
		this.executeTime = executeTime;
	}

	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Sys105mId))
			return false;
		Sys105mId castOther = (Sys105mId) other;

		return ((this.getSid() == castOther.getSid()) || (this.getSid() != null
				&& castOther.getSid() != null && this.getSid().equals(
				castOther.getSid())))
				&& ((this.getDbUser() == castOther.getDbUser()) || (this
						.getDbUser() != null
						&& castOther.getDbUser() != null && this.getDbUser()
						.equals(castOther.getDbUser())))
				&& ((this.getExecuteTime() == castOther.getExecuteTime()) || (this
						.getExecuteTime() != null
						&& castOther.getExecuteTime() != null && this
						.getExecuteTime().equals(castOther.getExecuteTime())))
				&& ((this.getPid() == castOther.getPid()) || (this.getPid() != null
						&& castOther.getPid() != null && this.getPid().equals(
						castOther.getPid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSid() == null ? 0 : this.getSid().hashCode());
		result = 37 * result
				+ (getDbUser() == null ? 0 : this.getDbUser().hashCode());
		result = 37
				* result
				+ (getExecuteTime() == null ? 0 : this.getExecuteTime()
						.hashCode());
		result = 37 * result
				+ (getPid() == null ? 0 : this.getPid().hashCode());
		return result;
	}

}
