package com.redsun.platf.entity.sys;
// default package
// Generated 2010/8/27 下午 06:02:54 by Hibernate Tools 3.3.0.GA

import java.util.Date;

import com.redsun.platf.entity.BaseEntity;

/**
 * 重要資料表維護作業
 * Sys116m generated by hbm2java
 */
public class Sys116m extends BaseEntity implements java.io.Serializable {

	private Sys116mId sys116mId;
	private Date creDate;
	private String isAuth;

	public Sys116m() {
	}

	public Sys116m(Sys116mId sys116mId) {
		this.sys116mId = sys116mId;
	}

	public Sys116m(Sys116mId id, Date creDate, String isAuth) {
		this.sys116mId = id;
		this.creDate = creDate;
		this.isAuth = isAuth;
	}

	public Date getCreDate() {
		return this.creDate;
	}

	public void setCreDate(Date creDate) {
		this.creDate = creDate;
	}

	public String getIsAuth() {
		return this.isAuth;
	}

	public void setIsAuth(String isAuth) {
		this.isAuth = isAuth;
	}

	public Sys116mId getSys116mId() {
	    return sys116mId;
	}

	public void setSys116mId(Sys116mId sys116mId) {
	    this.sys116mId = sys116mId;
	}

}
