package com.redsun.platf.entity.sys;

// default package
// Generated 2010/8/12 下午 05:52:38 by Hibernate Tools 3.3.0.GA

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.PrePersist;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.redsun.platf.entity.BaseEntity;

/**
 * 
 * 資料庫主機登入登出紀錄 Sys103m generated by hbm2java
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class Sys103m extends BaseEntity implements java.io.Serializable {

    private static final long serialVersionUID = -4762666177627983933L;
//    private Sys103mId sys103mid;
    private String terminal;
    private String ipAddress;
    private Date logoffDay;
    private String elapsedMinutes;

  

//    public Sys103m(Sys103mId sys103mid) {
//	this.sys103mid = sys103mid;
//    }
//
//    @PrePersist
//    public Sys103m getNewSys103m(Sys103m oSys103m) {
//	Sys103m obj = new Sys103m(oSys103m.getSys103mId());
//	obj.setTerminal(oSys103m.getTerminal());
//	obj.setIpAddress(oSys103m.getIpAddress());
//	obj.setLogoffDay(oSys103m.getLogoffDay());
//	obj.setElapsedMinutes(oSys103m.getElapsedMinutes());
//	return obj;
//    }
//
//    public Sys103m(Sys103mId id, String terminal, String ipAddress,
//	    Date logoffDay, String elapsedMinutes) {
//	this.sys103mid = id;
//	this.terminal = terminal;
//	this.ipAddress = ipAddress;
//	this.logoffDay = logoffDay;
//	this.elapsedMinutes = elapsedMinutes;
//    }
//
//    public Sys103mId getSys103mId() {
//	return this.sys103mid;
//    }


    public String getTerminal() {
	return this.terminal;
    }

    public void setTerminal(String terminal) {
	this.terminal = terminal;
    }

    public String getIpAddress() {
	return this.ipAddress;
    }

    public void setIpAddress(String ipAddress) {
	this.ipAddress = ipAddress;
    }

    public Date getLogoffDay() {
	return this.logoffDay;
    }

    public void setLogoffDay(Date logoffDay) {
	this.logoffDay = logoffDay;
    }

    public String getElapsedMinutes() {
	return this.elapsedMinutes;
    }

    public void setElapsedMinutes(String elapsedMinutes) {
	this.elapsedMinutes = elapsedMinutes;
    }

}
