package com.redsun.platf.entity.sys;
// default package
// Generated 2010/8/24 下午 03:34:30 by Hibernate Tools 3.3.0.GA

import java.io.Serializable;
import java.util.Date;

import com.redsun.platf.entity.BaseEntity;

/**
 * 資料庫主機重要帳號執行記錄
 * Sys104m generated by hbm2java
 */
public class Sys104m extends BaseEntity implements java.io.Serializable {

	private String seq;
	private String osHost;
	private String osUser;
	private Date logoffDay;
	private String cmdText;
	private Date creDate;

	public Sys104m() {
	}

	public Sys104m(String seq, String osHost, String osUser,
			Date creDate) {
		this.seq = seq;
		this.osHost = osHost;
		this.osUser = osUser;
		this.creDate = creDate;
	}

	public Sys104m(String seq, String osHost, String osUser,
			Date logoffDay, String cmdText, Date creDate) {
		this.seq = seq;
		this.osHost = osHost;
		this.osUser = osUser;
		this.logoffDay = logoffDay;
		this.cmdText = cmdText;
		this.creDate = creDate;
	}

	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	public String getOsHost() {
		return this.osHost;
	}

	public void setOsHost(String osHost) {
		this.osHost = osHost;
	}

	public String getOsUser() {
		return this.osUser;
	}

	public void setOsUser(String osUser) {
		this.osUser = osUser;
	}

	public Date getLogoffDay() {
		return this.logoffDay;
	}

	public void setLogoffDay(Date logoffDay) {
		this.logoffDay = logoffDay;
	}

	public String getCmdText() {
		return this.cmdText;
	}

	public void setCmdText(String cmdText) {
		this.cmdText = cmdText;
	}

	public Serializable getCreDate() {
		return this.creDate;
	}

	public void setCreDate(Date creDate) {
		this.creDate = creDate;
	}
	public Sys104m getNewSys104m(Sys104m obj){
		Sys104m sys104m = new Sys104m();
		sys104m.setCmdText(obj.getCmdText());
		sys104m.setCreDate(new Date());
		sys104m.setLogoffDay(obj.getLogoffDay());
		sys104m.setOsHost(obj.getOsHost());
		sys104m.setOsUser(obj.getOsUser());
		return sys104m;
	}
}
