package com.redsun.platf.entity.sys;


import java.util.Date;

import com.redsun.platf.entity.BaseEntity;

/**
 * 異常時間定義表格
 * Sys119m generated by hbm2java
 */
public class Sys119m extends BaseEntity implements java.io.Serializable {

	private String seq;
	private String sid;
	private String isAuth;
	private Date logonDay;
	private Date logoffDay;
	private String osHost;
	private String sidDes;
	private String creUser;
	private Date creDate;
	private String maiUser;
	private Date maiDate;

	public Sys119m() {
	}

	public Sys119m(String seq, String sid, String isAuth, Date logonDay,
			Date logoffDay) {
		this.seq = seq;
		this.sid = sid;
		this.isAuth = isAuth;
		this.logonDay = logonDay;
		this.logoffDay = logoffDay;
	}

	public Sys119m(String seq, String sid, String isAuth, Date logonDay,
			Date logoffDay, String osHost, String sidDes, String creUser,
			Date creDate, String maiUser, Date maiDate) {
		this.seq = seq;
		this.sid = sid;
		this.isAuth = isAuth;
		this.logonDay = logonDay;
		this.logoffDay = logoffDay;
		this.osHost = osHost;
		this.sidDes = sidDes;
		this.creUser = creUser;
		this.creDate = creDate;
		this.maiUser = maiUser;
		this.maiDate = maiDate;
	}

	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	public String getSid() {
		return this.sid;
	}

	public void setSid(String sid) {
		this.sid = sid;
	}

	public String getIsAuth() {
		return this.isAuth;
	}

	public void setIsAuth(String isAuth) {
		this.isAuth = isAuth;
	}

	public Date getLogonDay() {
		return this.logonDay;
	}

	public void setLogonDay(Date logonDay) {
		this.logonDay = logonDay;
	}

	public Date getLogoffDay() {
		return this.logoffDay;
	}

	public void setLogoffDay(Date logoffDay) {
		this.logoffDay = logoffDay;
	}

	public String getOsHost() {
		return this.osHost;
	}

	public void setOsHost(String osHost) {
		this.osHost = osHost;
	}

	public String getSidDes() {
		return this.sidDes;
	}

	public void setSidDes(String sidDes) {
		this.sidDes = sidDes;
	}

	public String getCreUser() {
		return this.creUser;
	}

	public void setCreUser(String creUser) {
		this.creUser = creUser;
	}

	public Date getCreDate() {
		return this.creDate;
	}

	public void setCreDate(Date creDate) {
		this.creDate = creDate;
	}

	public String getMaiUser() {
		return this.maiUser;
	}

	public void setMaiUser(String maiUser) {
		this.maiUser = maiUser;
	}

	public Date getMaiDate() {
		return this.maiDate;
	}

	public void setMaiDate(Date maiDate) {
		this.maiDate = maiDate;
	}

}
