package com.redsun.platf.entity.sys;
// default package
// Generated 2010/8/27 下午 06:02:54 by Hibernate Tools 3.3.0.GA

/**
 * Sys116mId generated by hbm2java
 */
public class Sys116mId implements java.io.Serializable {

	private String sid;
	private String tableOwner;
	private String tableName;

	public Sys116mId() {
	}

	public Sys116mId(String sid, String tableOwner, String tableName) {
		this.sid = sid;
		this.tableOwner = tableOwner;
		this.tableName = tableName;
	}

	public String getSid() {
		return this.sid;
	}

	public void setSid(String sid) {
		this.sid = sid;
	}

	public String getTableOwner() {
		return this.tableOwner;
	}

	public void setTableOwner(String tableOwner) {
		this.tableOwner = tableOwner;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Sys116mId))
			return false;
		Sys116mId castOther = (Sys116mId) other;

		return ((this.getSid() == castOther.getSid()) || (this.getSid() != null
				&& castOther.getSid() != null && this.getSid().equals(
				castOther.getSid())))
				&& ((this.getTableOwner() == castOther.getTableOwner()) || (this
						.getTableOwner() != null
						&& castOther.getTableOwner() != null && this
						.getTableOwner().equals(castOther.getTableOwner())))
				&& ((this.getTableName() == castOther.getTableName()) || (this
						.getTableName() != null
						&& castOther.getTableName() != null && this
						.getTableName().equals(castOther.getTableName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSid() == null ? 0 : this.getSid().hashCode());
		result = 37
				* result
				+ (getTableOwner() == null ? 0 : this.getTableOwner()
						.hashCode());
		result = 37 * result
				+ (getTableName() == null ? 0 : this.getTableName().hashCode());
		return result;
	}

}
