package com.redsun.platf.entity.sys;

// default package
// Generated 2010/8/12 下午 05:52:38 by Hibernate Tools 3.3.0.GA

import java.util.Date;

import javax.persistence.Entity;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.redsun.platf.entity.BaseEntity;

/**
 * Sys103mId generated by hbm2java
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class Sys103mId extends BaseEntity {

    private static final long serialVersionUID = -2263723530530102898L;
    private String osHost;
    private String osUser;
    private Date logonDay;

    public Sys103mId() {
    }

    public Sys103mId(String osHost, String osUser, Date logonDay) {
	this.osHost = osHost;
	this.osUser = osUser;
	this.logonDay = logonDay;
    }

    public String getOsHost() {
	return this.osHost;
    }

    public void setOsHost(String osHost) {
	this.osHost = osHost;
    }

    public String getOsUser() {
	return this.osUser;
    }

    public void setOsUser(String osUser) {
	this.osUser = osUser;
    }

    public Date getLogonDay() {
	return this.logonDay;
    }

    public void setLogonDay(Date logonDay) {
	this.logonDay = logonDay;
    }

    public boolean equals(Object other) {
	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof Sys103mId))
	    return false;
	Sys103mId castOther = (Sys103mId) other;

	return ((this.getOsHost() == castOther.getOsHost()) || (this
		.getOsHost() != null
		&& castOther.getOsHost() != null && this.getOsHost().equals(
		castOther.getOsHost())))
		&& ((this.getOsUser() == castOther.getOsUser()) || (this
			.getOsUser() != null
			&& castOther.getOsUser() != null && this.getOsUser()
			.equals(castOther.getOsUser())))
		&& ((this.getLogonDay() == castOther.getLogonDay()) || (this
			.getLogonDay() != null
			&& castOther.getLogonDay() != null && this
			.getLogonDay().equals(castOther.getLogonDay())));
    }

    public int hashCode() {
	int result = 17;

	result = 37 * result
		+ (getOsHost() == null ? 0 : this.getOsHost().hashCode());
	result = 37 * result
		+ (getOsUser() == null ? 0 : this.getOsUser().hashCode());
	result = 37 * result
		+ (getLogonDay() == null ? 0 : this.getLogonDay().hashCode());
	return result;
    }

}
